global using Microsoft.VisualStudio.TestTools.UnitTesting;
global using System;
global using System.Collections.Generic;
global using System.Globalization;
global using ToolBX.AssertBox;
global using ToolBX.AssertBox.Assertions;
global using ToolBX.Dummies;
global using ToolBX.SmartyStrings;
global using WhiteJackalStudio.TestTools;
